# Generated by Django 4.1.7 on 2023-07-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quizquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizcategory',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='quizcategory',
            name='details',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='level',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizquestion')),
            ],
        ),
    ]
