# Generated by Django 4.1.7 on 2023-07-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_title_quizcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='detail',
            field=models.TextField(default='not available'),
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='img',
            field=models.ImageField(default='/static/img/py1.jfif/', upload_to='py1.jfif/'),
        ),
    ]
