# Generated by Django 4.2.2 on 2023-08-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quizquestion_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='QuizAnswer',
        ),
    ]
