# Generated by Django 4.2.2 on 2023-08-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_result_delete_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='points',
            field=models.IntegerField(default='0'),
        ),
    ]
